#!/usr/bin/env perl

use strict;
use warnings;

BEGIN {
    use FindBin qw($Bin);
    use lib "$Bin/../../../lib";
    $ENV{DBIX_CONFIG_DIR} = "$Bin/../../../";
}


{
    package Eval::WithLexicals::Scratchpad;
    use vars qw($schema);
    use Judoon::Schema;
    $schema = Judoon::Schema->connect('Judoon::Schema');
}

use File::Which;
do +which('tinyrepl')

